src/IdentityServer.UI/ViewModels/Client/ClientClaimDto.cs
using System.ComponentModel.DataAnnotations;

namespace IdentityServer.UI.ViewModels.Client
{
	public class ClientClaimDto
	{
	    public int Id { get; set; }

	    [Required]
        public string Type { get; set; }

	    [Required]
        public string Value { get; set; }
	}
}

src/IdentityServer.UI/ViewModels/Client/ClientClaimsDto.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IdentityServer.UI.ViewModels.Client
{
	public class ClientClaimsDto
	{
		public ClientClaimsDto()
		{
			ClientClaims = new List<ClientClaimDto>();
		}

		public int ClientClaimId { get; set; }

		public int ClientId { get; set; }

	    public string ClientName { get; set; }

        [Required]
		public string Type { get; set; }

	    [Required]
        public string Value { get; set; }

		public List<ClientClaimDto> ClientClaims { get; set; }

		public int TotalCount { get; set; }

		public int PageSize { get; set; }	    
	}
}

src/IdentityServer.UI/ViewModels/Client/ClientCloneDto.cs
namespace IdentityServer.UI.ViewModels.Client
{
    public class ClientCloneDto : ClientDto
    {
        public string ClientIdOriginal { get; set; }

        public string ClientNameOriginal { get; set; }

        public bool CloneClientCorsOrigins { get; set; }

        public bool CloneClientRedirectUris { get; set; }

        public bool CloneClientIdPRestrictions { get; set; }

        public bool CloneClientPostLogoutRedirectUris { get; set; }

        public bool CloneClientGrantTypes { get; set; }

        public bool CloneClientScopes { get; set; }

        public bool CloneClientClaims { get; set; }

        public bool CloneClientProperties { get; set; }
    }
}

src/IdentityServer.UI/ViewModels/Client/ClientDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using IdentityServer.UI.ViewModels.Common;
using IdentityServer.UI.ViewModels.Enums;

namespace IdentityServer.UI.ViewModels.Client
{
    public class ClientDto
    {
        public ClientDto()
        {
            AllowedScopes = new List<string>();
            PostLogoutRedirectUris = new List<string>();
            RedirectUris = new List<string>();
            IdentityProviderRestrictions = new List<string>();
            AllowedCorsOrigins = new List<string>();
            AllowedGrantTypes = new List<string>();
            Claims = new List<ClientClaimDto>();
            ClientSecrets = new List<ClientSecretDto>();
            Properties = new List<ClientPropertyDto>();
        }

        public ClientType ClientType { get; set; }

        public int AbsoluteRefreshTokenLifetime { get; set; } = 2592000;
        public int AccessTokenLifetime { get; set; } = 3600;

        public int? ConsentLifetime { get; set; }

        public int AccessTokenType { get; set; }
        public List<SelectItemDto> AccessTokenTypes { get; set; }

        public bool AllowAccessTokensViaBrowser { get; set; }
        public bool AllowOfflineAccess { get; set; }
        public bool AllowPlainTextPkce { get; set; }
        public bool AllowRememberConsent { get; set; } = true;
        public bool AlwaysIncludeUserClaimsInIdToken { get; set; }
        public bool AlwaysSendClientClaims { get; set; }
        public int AuthorizationCodeLifetime { get; set; } = 300;

        public string FrontChannelLogoutUri { get; set; }
        public bool FrontChannelLogoutSessionRequired { get; set; } = true;
        public string BackChannelLogoutUri { get; set; }
        public bool BackChannelLogoutSessionRequired { get; set; } = true;

        [Required]
        public string ClientId { get; set; }

        [Required]
        public string ClientName { get; set; }

        public string ClientUri { get; set; }

        public string Description { get; set; }

        public bool Enabled { get; set; } = true;
        public bool EnableLocalLogin { get; set; } = true;
        public int Id { get; set; }
        public int IdentityTokenLifetime { get; set; } = 300;
        public bool IncludeJwtId { get; set; }
        public string LogoUri { get; set; }

        public string ClientClaimsPrefix { get; set; } = "client_";

        public string PairWiseSubjectSalt { get; set; }

        public string ProtocolType { get; set; } = "oidc";

        public List<SelectItemDto> ProtocolTypes { get; set; }

        public int RefreshTokenExpiration { get; set; } = 1;
        public List<SelectItemDto> RefreshTokenExpirations { get; set; }

        public int RefreshTokenUsage { get; set; } = 1;
        public List<SelectItemDto> RefreshTokenUsages { get; set; }

        public int SlidingRefreshTokenLifetime { get; set; } = 1296000;

        public bool RequireClientSecret { get; set; } = true;
        public bool RequireConsent { get; set; } = true;
        public bool RequirePkce { get; set; }
        public bool UpdateAccessTokenClaimsOnRefresh { get; set; }

        public List<string> PostLogoutRedirectUris { get; set; }
        public string PostLogoutRedirectUrisItems { get; set; }

        public List<string> IdentityProviderRestrictions { get; set; }
        public string IdentityProviderRestrictionsItems { get; set; }

        public List<string> RedirectUris { get; set; }
        public string RedirectUrisItems { get; set; }

        public List<string> AllowedCorsOrigins { get; set; }
        public string AllowedCorsOriginsItems { get; set; }

        public List<string> AllowedGrantTypes { get; set; }
        public string AllowedGrantTypesItems { get; set; }

        public List<string> AllowedScopes { get; set; }
        public string AllowedScopesItems { get; set; }

        public List<ClientClaimDto> Claims { get; set; }
        public List<ClientSecretDto> ClientSecrets { get; set; }
        public List<ClientPropertyDto> Properties { get; set; }

        public DateTime? Updated { get; set; }
        public DateTime? LastAccessed { get; set; }

        public int? UserSsoLifetime { get; set; }
        public string UserCodeType { get; set; }
        public int DeviceCodeLifetime { get; set; } = 300;

        public bool NonEditable { get; set; }
    }
}

src/IdentityServer.UI/ViewModels/Client/ClientPropertiesDto.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IdentityServer.UI.ViewModels.Client
{
    public class ClientPropertiesDto
    {
        public ClientPropertiesDto()
        {
            ClientProperties = new List<ClientPropertyDto>();
        }

        public int ClientPropertyId { get; set; }

        public int ClientId { get; set; }

        public string ClientName { get; set; }

        [Required]
        public string Key { get; set; }

        [Required]
        public string Value { get; set; }

        public List<ClientPropertyDto> ClientProperties { get; set; }

        public int TotalCount { get; set; }

        public int PageSize { get; set; }        
    }
}

src/IdentityServer.UI/ViewModels/Client/ClientPropertyDto.cs
namespace IdentityServer.UI.ViewModels.Client
{
    public class ClientPropertyDto
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    }
}

src/IdentityServer.UI/ViewModels/Client/ClientSecretDto.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace IdentityServer.UI.ViewModels.Client
{
    public class ClientSecretDto
    {
        [Required]
        public string Type { get; set; } = "SharedSecret";

		public int Id { get; set; }

		public string Description { get; set; }

        [Required]
		public string Value { get; set; }

		public DateTime? Expiration { get; set; }

        public DateTime Created { get; set; }
	}
}

src/IdentityServer.UI/Controllers/ConfigurationController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using IdentityServer.UI.Configuration.Constants;
using IdentityServer.UI.ExceptionHandling;
using IdentityServer.UI.Services.Identity.Interfaces;
using IdentityServer.UI.Configuration;
using IdentityServer.UI.ViewModels.Identity;
using IdentityServer.UI.ViewModels.Client;
using IdentityServer.UI.Helpers;
using IdentityServer.UI.ViewModels.Api;

namespace IdentityServer.UI.Controllers
{
    [Authorize(Policy = AuthorizationConsts.AdministrationPolicy)]
    [TypeFilter(typeof(ControllerExceptionFilterAttribute))]
    public class ConfigurationController : BaseController
    {
        private readonly IIdentityResourceService _identityResourceService;
        private readonly IApiResourceService _apiResourceService;
        private readonly IClientService _clientService;
        private readonly IStringLocalizer<ConfigurationController> _localizer;

        public ConfigurationController(IIdentityResourceService identityResourceService,
            IApiResourceService apiResourceService,
            IClientService clientService,
            IStringLocalizer<ConfigurationController> localizer,
            ILogger<ConfigurationController> logger)
            : base(logger)
        {
            _identityResourceService = identityResourceService;
            _apiResourceService = apiResourceService;
            _clientService = clientService;
            _localizer = localizer;
        }

        [HttpGet]
        [Route("[controller]/[action]")]
        [Route("[controller]/[action]/{id:int}")]
        public async Task<IActionResult> Client(int id)
        {
            if (id == 0)
            {
                var clientDto = _clientService.BuildClientViewModel();
                return View(clientDto);
            }

            var client = await _clientService.GetClientAsync((int)id);
            client = _clientService.BuildClientViewModel(client);

            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Client(ClientDto client)
        {
            client = _clientService.BuildClientViewModel(client);

            if (!ModelState.IsValid)
            {
                return View(client);
            }

            //Add new client
            if (client.Id == 0)
            {
                var clientId = await _clientService.AddClientAsync(client);
                SuccessNotification(string.Format(_localizer["SuccessAddClient"], client.ClientId), _localizer["SuccessTitle"]);

                return RedirectToAction(nameof(Client), new { Id = clientId });
            }

            //Update client
            await _clientService.UpdateClientAsync(client);
            SuccessNotification(string.Format(_localizer["SuccessUpdateClient"], client.ClientId), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(Client), new { client.Id });
        }

        [HttpGet]
        public async Task<IActionResult> ClientClone(int id)
        {
            if (id == 0) return NotFound();

            var clientDto = await _clientService.GetClientAsync(id);
            var client = _clientService.BuildClientCloneViewModel(id, clientDto);

            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientClone(ClientCloneDto client)
        {
            if (!ModelState.IsValid)
            {
                return View(client);
            }

            var newClientId = await _clientService.CloneClientAsync(client);
            SuccessNotification(string.Format(_localizer["SuccessClientClone"], client.ClientId), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(Client), new { Id = newClientId });
        }

        [HttpGet]
        public async Task<IActionResult> ClientDelete(int id)
        {
            if (id == 0) return NotFound();

            var client = await _clientService.GetClientAsync(id);

            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientDelete(ClientDto client)
        {
            await _clientService.RemoveClientAsync(client);

            SuccessNotification(_localizer["SuccessClientDelete"], _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(Clients));
        }

        [HttpGet]
        public async Task<IActionResult> ClientClaims(int id, int? page)
        {
            if (id == 0) return NotFound();

            var claims = await _clientService.GetClientClaimsAsync(id, page ?? 1);

            return View(claims);
        }

        [HttpGet]
        public async Task<IActionResult> ClientProperties(int id, int? page)
        {
            if (id == 0) return NotFound();

            var properties = await _clientService.GetClientPropertiesAsync(id, page ?? 1);

            return View(properties);
        }

        [HttpGet]
        public async Task<IActionResult> ApiResourceProperties(int id, int? page)
        {
            if (id == 0) return NotFound();

            var properties = await _apiResourceService.GetApiResourcePropertiesAsync(id, page ?? 1);

            return View(properties);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ApiResourceProperties(ApiResourcePropertiesDto apiResourceProperty)
        {
            if (!ModelState.IsValid)
            {
                return View(apiResourceProperty);
            }

            await _apiResourceService.AddApiResourcePropertyAsync(apiResourceProperty);
            SuccessNotification(string.Format(_localizer["SuccessAddApiResourceProperty"], apiResourceProperty.Key, apiResourceProperty.ApiResourceName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ApiResourceProperties), new { Id = apiResourceProperty.ApiResourceId });
        }

        [HttpGet]
        public async Task<IActionResult> IdentityResourceProperties(int id, int? page)
        {
            if (id == 0) return NotFound();

            var properties = await _identityResourceService.GetIdentityResourcePropertiesAsync(id, page ?? 1);

            return View(properties);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> IdentityResourceProperties(IdentityResourcePropertiesDto identityResourceProperty)
        {
            if (!ModelState.IsValid)
            {
                return View(identityResourceProperty);
            }

            await _identityResourceService.AddIdentityResourcePropertyAsync(identityResourceProperty);
            SuccessNotification(string.Format(_localizer["SuccessAddIdentityResourceProperty"], identityResourceProperty.Value, identityResourceProperty.IdentityResourceName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(IdentityResourceProperties), new { Id = identityResourceProperty.IdentityResourceId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientProperties(ClientPropertiesDto clientProperty)
        {
            if (!ModelState.IsValid)
            {
                return View(clientProperty);
            }

            await _clientService.AddClientPropertyAsync(clientProperty);
            SuccessNotification(string.Format(_localizer["SuccessAddClientProperty"], clientProperty.ClientId, clientProperty.ClientName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ClientProperties), new { Id = clientProperty.ClientId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientClaims(ClientClaimsDto clientClaim)
        {
            if (!ModelState.IsValid)
            {
                return View(clientClaim);
            }

            await _clientService.AddClientClaimAsync(clientClaim);
            SuccessNotification(string.Format(_localizer["SuccessAddClientClaim"], clientClaim.Value, clientClaim.ClientName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ClientClaims), new { Id = clientClaim.ClientId });
        }

        [HttpGet]
        public async Task<IActionResult> ClientClaimDelete(int id)
        {
            if (id == 0) return NotFound();

            var clientClaim = await _clientService.GetClientClaimAsync(id);

            return View(nameof(ClientClaimDelete), clientClaim);
        }

        [HttpGet]
        public async Task<IActionResult> ClientPropertyDelete(int id)
        {
            if (id == 0) return NotFound();

            var clientProperty = await _clientService.GetClientPropertyAsync(id);

            return View(nameof(ClientPropertyDelete), clientProperty);
        }

        [HttpGet]
        public async Task<IActionResult> ApiResourcePropertyDelete(int id)
        {
            if (id == 0) return NotFound();

            var apiResourceProperty = await _apiResourceService.GetApiResourcePropertyAsync(id);

            return View(nameof(ApiResourcePropertyDelete), apiResourceProperty);
        }

        [HttpGet]
        public async Task<IActionResult> IdentityResourcePropertyDelete(int id)
        {
            if (id == 0) return NotFound();

            var identityResourceProperty = await _identityResourceService.GetIdentityResourcePropertyAsync(id);

            return View(nameof(IdentityResourcePropertyDelete), identityResourceProperty);
        }

        [HttpPost]
        public async Task<IActionResult> ClientClaimDelete(ClientClaimsDto clientClaim)
        {
            await _clientService.DeleteClientClaimAsync(clientClaim);
            SuccessNotification(_localizer["SuccessDeleteClientClaim"], _localizer["SuccessTitle"]);

src/IdentityServer.UI/Views/Configuration/Client/Section/ActionButtons.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model IdentityServer.UI.ViewModels.Client.ClientDto
@inject IViewLocalizer Localizer

<div class="row client">
	<div class="col-md-12 action-butons">
		<button class="client-save-button btn btn-primary">@Localizer["ButtonSave"]</button>

		@if (Model.Id != 0)
		{
			<a asp-action="ClientClone" asp-route-id="@Model.Id" target="_blank" class="btn btn-outline-primary">@Localizer["ButtonClone"]</a>
			<a asp-action="ClientDelete" asp-route-id="@Model.Id" class="btn btn-danger">@Localizer["ButtonDelete"]</a>
		}
	</div>
</div>

src/IdentityServer.UI/Views/Configuration/Client/Section/Basics.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model IdentityServer.UI.ViewModels.Client.ClientDto
@inject IViewLocalizer Localizer
<!--Hidden -->
<input type="hidden" asp-for="Id" />

<div class="card mt-3">
	<h5 class="card-header">@Localizer["PanelTitle"]</h5>
	<div class="card-body">
		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="Enabled" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "Enabled")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="Enabled" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Input - text -->
		<div class="form-group row">
			<label asp-for="Description" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "Description")
			</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" asp-for="Description">
			</div>
		</div>

		<!--Select-->
		<div class="form-group row">
			<label asp-for="ProtocolType" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "ProtocolType")
			</label>
			<div class="col-sm-9">
				<select asp-for="ProtocolType" asp-items="@(new SelectList(Model.ProtocolTypes,"Id","Text"))" class="form-control single-select"></select>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="RequireClientSecret" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "RequireClientSecret")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="RequireClientSecret" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="RequirePkce" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "RequirePkce")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="RequirePkce" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="AllowPlainTextPkce" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowPlainTextPkce")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="AllowPlainTextPkce" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="AllowOfflineAccess" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowOfflineAccess")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="AllowOfflineAccess" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="AllowAccessTokensViaBrowser" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowAccessTokensViaBrowser")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="AllowAccessTokensViaBrowser" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Select with tags-->
		<div class="form-group row">
			<label asp-for="AllowedScopes" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowedScopes")
			</label>
			<div class="col-sm-9">
				<picker id="AllowedScopesItems" multiple-select="true" min-search-text="2"
				        selected-items="@Model.AllowedScopes" url="@Url.Action("SearchScopes","Configuration")?scope"
				        search-input-placeholder="@Localizer["PickerSearchItemPlaceholder"].Value"
				        selected-items-title="@Localizer["PickerSelectedItemsTitle"].Value" 
				        search-result-title="@Localizer["PickerSearchResultTitle"].Value"
				        suggested-items-title="@Localizer["PickerSuggestedItemsTitle"].Value" 
				        no-item-selected-title="@Localizer["PickerNoItemSelectedTitle"].Value" 
				        show-all-items-title="@Localizer["PickerShowAllItemsTitle"].Value"
				        item-already-selected-title="@Localizer["PickerItemAlreadySelectedTitle"].Value">
				</picker>
			</div>
		</div>


		<!--Select with tags-->
		<div class="form-group row">
			<label asp-for="RedirectUris" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "RedirectUris")
			</label>
			<div class="col-sm-9">
				<picker id="RedirectUrisItems" multiple-select="true" min-search-text="2"
				        selected-items="@Model.RedirectUris"
				        search-input-placeholder="@Localizer["PickerSearchItemPlaceholder"].Value"
				        selected-items-title="@Localizer["PickerSelectedItemsTitle"].Value" 
				        search-result-title="@Localizer["PickerSearchResultTitle"].Value"
				        suggested-items-title="@Localizer["PickerSuggestedItemsTitle"].Value" 
				        no-item-selected-title="@Localizer["PickerNoItemSelectedTitle"].Value" 
				        show-all-items-title="@Localizer["PickerShowAllItemsTitle"].Value"
				        item-already-selected-title="@Localizer["PickerItemAlreadySelectedTitle"].Value">
				</picker>
			</div>
		</div>

		<!--Select with tags-->
		<div class="form-group row">
			<label asp-for="AllowedGrantTypes" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowedGrantTypes")
			</label>
			<div class="col-sm-9">
				<picker id="AllowedGrantTypesItems" multiple-select="true" min-search-text="2"
						url="@Url.Action("SearchGrantTypes","Configuration")?grant"
				        selected-items="@Model.AllowedGrantTypes"
				        search-input-placeholder="@Localizer["PickerSearchItemPlaceholder"].Value"
				        selected-items-title="@Localizer["PickerSelectedItemsTitle"].Value" 
				        search-result-title="@Localizer["PickerSearchResultTitle"].Value"
				        suggested-items-title="@Localizer["PickerSuggestedItemsTitle"].Value" 
				        no-item-selected-title="@Localizer["PickerNoItemSelectedTitle"].Value" 
				        show-all-items-title="@Localizer["PickerShowAllItemsTitle"].Value"
				        item-already-selected-title="@Localizer["PickerItemAlreadySelectedTitle"].Value">
				</picker>
			</div>
		</div>

		<!--Button-->
		<div class="form-group row">
			<label asp-for="ClientSecrets" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "ClientSecrets")
			</label>
			<div class="col-sm-9">
				<a asp-action="ClientSecrets" asp-route-id="@Model.Id" target="_blank" class="btn btn-primary">@Localizer["ButtonManageClientSecrets"]</a>
			</div>
		</div>


		<!--Button-->
		<div class="form-group row">
			<label asp-for="Properties" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "Properties")
			</label>
			<div class="col-sm-9">
				<a asp-action="ClientProperties" asp-route-id="@Model.Id" target="_blank" class="btn btn-primary">@Localizer["ButtonManageClientProperties"]</a>
			</div>
		</div>
	</div>
</div>

src/IdentityServer.UI/Views/Configuration/Client/Section/Consent.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model IdentityServer.UI.ViewModels.Client.ClientDto
@inject IViewLocalizer Localizer

<div class="card mt-3">
	<h5 class="card-header">@Localizer["PageTitle"]</h5>
	<div class="card-body">
		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="RequireConsent" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "RequireConsent")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="RequireConsent" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="AllowRememberConsent" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowRememberConsent")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="AllowRememberConsent" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Input - text -->
		<div class="form-group row">
			<label asp-for="ClientUri" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "ClientUri")
			</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" asp-for="ClientUri">
			</div>
		</div>

		<!--Input - text -->
		<div class="form-group row">
			<label asp-for="LogoUri" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "LogoUri")
			</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" asp-for="LogoUri">
			</div>
		</div>
	</div>
</div>

src/IdentityServer.UI/Views/Configuration/Client/Section/DeviceFlow.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model IdentityServer.UI.ViewModels.Client.ClientDto
@inject IViewLocalizer Localizer

<div class="card mt-3">
	<h5 class="card-header">@Localizer["PanelTitle"]</h5>
	<div class="card-body">
		<!--Input - text -->
		<div class="form-group row">
			<label asp-for="UserCodeType" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "UserCodeType")
			</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" asp-for="UserCodeType">
			</div>
		</div>
		
		<!--Input - number -->
		<div class="form-group row">
			<label asp-for="DeviceCodeLifetime" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "DeviceCodeLifetime")
			</label>
			<div class="col-sm-9">
				<input type="number" class="form-control" asp-for="DeviceCodeLifetime">
			</div>
		</div>
	</div>
</div>